### ISSUE TITLE
Feature request: count for user text selection

### ISSUE THREAD

**Issue by benfrain** [Microsoft/vscode-wordcount#12]
It would be great if when selecting an area of text within a larger document, Word Count updated to show the count inside the user text selection. Removing the selection would revert the display back to the count for the entire document.

**Comment by gregvanl** [comment]
Closing as vscode-wordcount is a simple VS Code extension example. There are other extension on the Marketplace such as https://marketplace.visualstudio.com/items?itemName=kirozen.wordcounter which do the selection word count.

**Comment by uogbuji** [comment]
Extremely silly for a text editor to require you to install an extension in order to have a word count feature.
