### ISSUE TITLE
"Property '_statusBarItem' has no initializer" error.

### ISSUE THREAD

**Issue by reyou** [Microsoft/vscode-wordcount#16]
I am following documentation below;
https://code.visualstudio.com/docs/extensions/example-word-count#_update-the-status-bar

If I use code snippet at the page, or here I am getting following error:

> message: 'Property '_statusBarItem' has no initializer and is not definitely assigned in the constructor.'

VS Code configured to use TypeScript 2.7.2.

Am I missing something here?

Error SS:

![image](https://user-images.githubusercontent.com/6571483/37611612-2ad74930-2b79-11e8-97f7-5ca830fd57a4.png)

**Comment by gregvanl** [comment]
Thanks for calling this out. This is due to TypeScript 2.7+ setting `--strictPropertyInitialization` on by default. Fixed in the VS Code documentation with https://github.com/Microsoft/vscode-docs/commit/06f622eddc4156db015d6375d2c372305383189d.

**Comment by reyou** [comment]
Thanks a lot!
