### ISSUE TITLE
Suggestion: Ability to count words in non-empty selection

### ISSUE THREAD

**Issue by toohuman** [Microsoft/vscode-wordcount#17]
Hello,

I would love to see the ability to select a couple of paragraphs and have the word count reflect the number of words contained in the selection.

Thanks,
Michael.

**Comment by gregvanl** [comment]
Hi @toohuman, vscode-wordcount is a simple VS Code extension example. There are other extension on the Marketplace such as https://marketplace.visualstudio.com/items?itemName=kirozen.wordcounter which do the selection word count.
