### ISSUE TITLE
Word count in LaTeX

### ISSUE THREAD

**Issue by psyguy** [Microsoft/vscode-wordcount#18]
Are you planning to add support of TeX in the extension?
Thanks in advance.

**Comment by gregvanl** [comment]
Hi @ihaqi, vscode-wordcount is a simple VS Code extension example. There are other extensions on the Marketplace such as https://marketplace.visualstudio.com/items?itemName=James-Yu.latex-workshop which provide good LaTeX support, including word count through TeXcount.
