### ISSUE TITLE
Average read time output

### ISSUE THREAD

**Issue by nickjj** [Microsoft/vscode-wordcount#7]
It would be nice if the average read time were output in addition to the word count. A `wordsReadPerMinute` setting could be exposed to configure it (defaulting to 200).

Typically in a Markdown writing scenario word count and average read time go hand in hand.

**Comment by Haroenv** [comment]
https://marketplace.visualstudio.com/items?itemName=vinzi.wordscounter and https://marketplace.visualstudio.com/items?itemName=kirozen.wordcounter both have this feature

**Comment by nickjj** [comment]
Thanks, yeah I've been using https://marketplace.visualstudio.com/items?itemName=kirozen.wordcounter for a while now and it works great.

**Comment by gregvanl** [comment]
Closing as this is just a simple extension example and there is a community extension which meets the need for average read time.
